// Simulacion de respuesta de backend para la grafica promedio de glucosa.
// La idea es que frontend consuma este contrato tal como si fuera el payload
// del servicio, con filtros disponibles y datos listos para pintar.

export const DataGlucosaContrato = {
  semana: {
    metadatos: {
      unidad: "mg/dL",
      resolucion: "dia",
      periodo: "semana",
      hl7code: "15074-8",
      loinccode: "2339-0",
    },
    filtros: [
      { value: "2026-04-13", label: "Lun 13 Abr - Dom 19 Abr" },
      { value: "2026-04-20", label: "Lun 20 Abr - Dom 26 Abr" },
      { value: "2026-04-27", label: "Lun 27 Abr - Dom 03 May" },
    ],
    seleccionActual: "2026-04-27",
    seriesPorFiltro: {
      "2026-04-13": {
        etiquetaFiltro: "Lun 13 Abr - Dom 19 Abr",
        puntos: [
          { etiqueta: "lun", toma: 84, tipo: "ayuno" },
          { etiqueta: "lun", toma: 126, tipo: "postprandial" },
          { etiqueta: "mar", toma: 88, tipo: "ayuno" },
          { etiqueta: "mar", toma: 132, tipo: "postprandial" },
          { etiqueta: "mie", toma: 90, tipo: "ayuno" },
          { etiqueta: "mie", toma: 128, tipo: "postprandial" },
          { etiqueta: "jue", toma: 86, tipo: "ayuno" },
          { etiqueta: "jue", toma: 124, tipo: "postprandial" },
          { etiqueta: "vie", toma: 92, tipo: "ayuno" },
          { etiqueta: "vie", toma: 136, tipo: "postprandial" },
          { etiqueta: "sab", toma: 89, tipo: "ayuno" },
          { etiqueta: "sab", toma: 121, tipo: "postprandial" },
          { etiqueta: "dom", toma: 87, tipo: "ayuno" },
          { etiqueta: "dom", toma: 118, tipo: "postprandial" },
        ],
      },
      "2026-04-20": {
        etiquetaFiltro: "Lun 20 Abr - Dom 26 Abr",
        puntos: [
          { etiqueta: "lun", toma: 82, tipo: "ayuno" },
          { etiqueta: "lun", toma: 120, tipo: "postprandial" },
          { etiqueta: "mar", toma: 85, tipo: "ayuno" },
          { etiqueta: "mar", toma: 127, tipo: "postprandial" },
          { etiqueta: "mie", toma: 91, tipo: "ayuno" },
          { etiqueta: "mie", toma: 130, tipo: "postprandial" },
          { etiqueta: "jue", toma: 88, tipo: "ayuno" },
          { etiqueta: "jue", toma: 125, tipo: "postprandial" },
          { etiqueta: "vie", toma: 93, tipo: "ayuno" },
          { etiqueta: "vie", toma: 138, tipo: "postprandial" },
          { etiqueta: "sab", toma: 86, tipo: "ayuno" },
          { etiqueta: "sab", toma: 123, tipo: "postprandial" },
          { etiqueta: "dom", toma: 84, tipo: "ayuno" },
          { etiqueta: "dom", toma: 119, tipo: "postprandial" },
        ],
      },
      "2026-04-27": {
        etiquetaFiltro: "Lun 27 Abr - Dom 03 May",
        puntos: [
          { etiqueta: "lun", toma: 81, tipo: "ayuno" },
          { etiqueta: "lun", toma: 117, tipo: "postprandial" },
          { etiqueta: "mar", toma: 83, tipo: "ayuno" },
          { etiqueta: "mar", toma: 122, tipo: "postprandial" },
          { etiqueta: "mie", toma: 87, tipo: "ayuno" },
          { etiqueta: "mie", toma: 129, tipo: "postprandial" },
          { etiqueta: "jue", toma: 85, tipo: "ayuno" },
          { etiqueta: "jue", toma: 126, tipo: "postprandial" },
          { etiqueta: "vie", toma: 90, tipo: "ayuno" },
          { etiqueta: "vie", toma: 133, tipo: "postprandial" },
          { etiqueta: "sab", toma: 88, tipo: "ayuno" },
          { etiqueta: "sab", toma: 124, tipo: "postprandial" },
          { etiqueta: "dom", toma: 86, tipo: "ayuno" },
          { etiqueta: "dom", toma: 120, tipo: "postprandial" },
        ],
      },
    },
  },

  mes: {
    metadatos: {
      unidad: "mg/dL",
      resolucion: "dia",
      periodo: "mes",
    },
    filtros: [
      { value: "2026-03", label: "Marzo - 2026" },
      { value: "2026-04", label: "Abril - 2026" },
      { value: "2026-05", label: "Mayo - 2026" },
    ],
    seleccionActual: "2026-04",
    seriesPorFiltro: {
      "2026-03": {
        etiquetaFiltro: "Marzo - 2026",
        puntos: [
          { etiqueta: "1", toma: 86, tipo: "ayuno" },
          { etiqueta: "1", toma: 122, tipo: "postprandial" },
          { etiqueta: "2", toma: 84, tipo: "ayuno" },
          { etiqueta: "2", toma: 119, tipo: "postprandial" },
          { etiqueta: "3", toma: 89, tipo: "ayuno" },
          { etiqueta: "3", toma: 127, tipo: "postprandial" },
          { etiqueta: "4", toma: 91, tipo: "ayuno" },
          { etiqueta: "4", toma: 132, tipo: "postprandial" },
          { etiqueta: "5", toma: 88, tipo: "ayuno" },
          { etiqueta: "5", toma: 125, tipo: "postprandial" },
          { etiqueta: "6", toma: 83, tipo: "ayuno" },
          { etiqueta: "6", toma: 118, tipo: "postprandial" },
          { etiqueta: "7", toma: 85, tipo: "ayuno" },
          { etiqueta: "7", toma: 121, tipo: "postprandial" },
          { etiqueta: "8", toma: 87, tipo: "ayuno" },
          { etiqueta: "8", toma: 126, tipo: "postprandial" },
          { etiqueta: "9", toma: 90, tipo: "ayuno" },
          { etiqueta: "9", toma: 130, tipo: "postprandial" },
          { etiqueta: "10", toma: 86, tipo: "ayuno" },
          { etiqueta: "10", toma: 123, tipo: "postprandial" },
          { etiqueta: "11", toma: 82, tipo: "ayuno" },
          { etiqueta: "11", toma: 117, tipo: "postprandial" },
          { etiqueta: "12", toma: 84, tipo: "ayuno" },
          { etiqueta: "12", toma: 120, tipo: "postprandial" },
          { etiqueta: "13", toma: 89, tipo: "ayuno" },
          { etiqueta: "13", toma: 129, tipo: "postprandial" },
          { etiqueta: "14", toma: 92, tipo: "ayuno" },
          { etiqueta: "14", toma: 134, tipo: "postprandial" },
          { etiqueta: "15", toma: 88, tipo: "ayuno" },
          { etiqueta: "15", toma: 126, tipo: "postprandial" },
          { etiqueta: "16", toma: 85, tipo: "ayuno" },
          { etiqueta: "16", toma: 121, tipo: "postprandial" },
          { etiqueta: "17", toma: 83, tipo: "ayuno" },
          { etiqueta: "17", toma: 116, tipo: "postprandial" },
          { etiqueta: "18", toma: 86, tipo: "ayuno" },
          { etiqueta: "18", toma: 124, tipo: "postprandial" },
          { etiqueta: "19", toma: 90, tipo: "ayuno" },
          { etiqueta: "19", toma: 131, tipo: "postprandial" },
          { etiqueta: "20", toma: 91, tipo: "ayuno" },
          { etiqueta: "20", toma: 133, tipo: "postprandial" },
          { etiqueta: "21", toma: 87, tipo: "ayuno" },
          { etiqueta: "21", toma: 127, tipo: "postprandial" },
          { etiqueta: "22", toma: 84, tipo: "ayuno" },
          { etiqueta: "22", toma: 120, tipo: "postprandial" },
          { etiqueta: "23", toma: 82, tipo: "ayuno" },
          { etiqueta: "23", toma: 118, tipo: "postprandial" },
          { etiqueta: "24", toma: 85, tipo: "ayuno" },
          { etiqueta: "24", toma: 123, tipo: "postprandial" },
          { etiqueta: "25", toma: 89, tipo: "ayuno" },
          { etiqueta: "25", toma: 128, tipo: "postprandial" },
          { etiqueta: "26", toma: 93, tipo: "ayuno" },
          { etiqueta: "26", toma: 136, tipo: "postprandial" },
          { etiqueta: "27", toma: 90, tipo: "ayuno" },
          { etiqueta: "27", toma: 129, tipo: "postprandial" },
          { etiqueta: "28", toma: 86, tipo: "ayuno" },
          { etiqueta: "28", toma: 122, tipo: "postprandial" },
          { etiqueta: "29", toma: 84, tipo: "ayuno" },
          { etiqueta: "29", toma: 119, tipo: "postprandial" },
          { etiqueta: "30", toma: 88, tipo: "ayuno" },
          { etiqueta: "30", toma: 125, tipo: "postprandial" },
          { etiqueta: "31", toma: 91, tipo: "ayuno" },
          { etiqueta: "31", toma: 132, tipo: "postprandial" },
        ],
      },
      "2026-04": {
        etiquetaFiltro: "Abril - 2026",
        puntos: [
          { etiqueta: "1", toma: 84, tipo: "ayuno" },
          { etiqueta: "1", toma: 120, tipo: "postprandial" },
          { etiqueta: "2", toma: 82, tipo: "ayuno" },
          { etiqueta: "2", toma: 116, tipo: "postprandial" },
          { etiqueta: "3", toma: 86, tipo: "ayuno" },
          { etiqueta: "3", toma: 124, tipo: "postprandial" },
          { etiqueta: "4", toma: 89, tipo: "ayuno" },
          { etiqueta: "4", toma: 130, tipo: "postprandial" },
          { etiqueta: "5", toma: 87, tipo: "ayuno" },
          { etiqueta: "5", toma: 126, tipo: "postprandial" },
          { etiqueta: "6", toma: 83, tipo: "ayuno" },
          { etiqueta: "6", toma: 118, tipo: "postprandial" },
          { etiqueta: "7", toma: 85, tipo: "ayuno" },
          { etiqueta: "7", toma: 121, tipo: "postprandial" },
          { etiqueta: "8", toma: 88, tipo: "ayuno" },
          { etiqueta: "8", toma: 127, tipo: "postprandial" },
          { etiqueta: "9", toma: 90, tipo: "ayuno" },
          { etiqueta: "9", toma: 131, tipo: "postprandial" },
          { etiqueta: "10", toma: 86, tipo: "ayuno" },
          { etiqueta: "10", toma: 123, tipo: "postprandial" },
          { etiqueta: "11", toma: 84, tipo: "ayuno" },
          { etiqueta: "11", toma: 119, tipo: "postprandial" },
          { etiqueta: "12", toma: 82, tipo: "ayuno" },
          { etiqueta: "12", toma: 117, tipo: "postprandial" },
          { etiqueta: "13", toma: 85, tipo: "ayuno" },
          { etiqueta: "13", toma: 122, tipo: "postprandial" },
          { etiqueta: "14", toma: 89, tipo: "ayuno" },
          { etiqueta: "14", toma: 128, tipo: "postprandial" },
          { etiqueta: "15", toma: 91, tipo: "ayuno" },
          { etiqueta: "15", toma: 133, tipo: "postprandial" },
          { etiqueta: "16", toma: 88, tipo: "ayuno" },
          { etiqueta: "16", toma: 126, tipo: "postprandial" },
          { etiqueta: "17", toma: 84, tipo: "ayuno" },
          { etiqueta: "17", toma: 120, tipo: "postprandial" },
          { etiqueta: "18", toma: 83, tipo: "ayuno" },
          { etiqueta: "18", toma: 118, tipo: "postprandial" },
          { etiqueta: "19", toma: 86, tipo: "ayuno" },
          { etiqueta: "19", toma: 124, tipo: "postprandial" },
          { etiqueta: "20", toma: 90, tipo: "ayuno" },
          { etiqueta: "20", toma: 132, tipo: "postprandial" },
          { etiqueta: "21", toma: 92, tipo: "ayuno" },
          { etiqueta: "21", toma: 135, tipo: "postprandial" },
          { etiqueta: "22", toma: 89, tipo: "ayuno" },
          { etiqueta: "22", toma: 129, tipo: "postprandial" },
          { etiqueta: "23", toma: 85, tipo: "ayuno" },
          { etiqueta: "23", toma: 121, tipo: "postprandial" },
          { etiqueta: "24", toma: 83, tipo: "ayuno" },
          { etiqueta: "24", toma: 117, tipo: "postprandial" },
          { etiqueta: "25", toma: 87, tipo: "ayuno" },
          { etiqueta: "25", toma: 125, tipo: "postprandial" },
          { etiqueta: "26", toma: 90, tipo: "ayuno" },
          { etiqueta: "26", toma: 131, tipo: "postprandial" },
          { etiqueta: "27", toma: 88, tipo: "ayuno" },
          { etiqueta: "27", toma: 127, tipo: "postprandial" },
          { etiqueta: "28", toma: 84, tipo: "ayuno" },
          { etiqueta: "28", toma: 120, tipo: "postprandial" },
          { etiqueta: "29", toma: 82, tipo: "ayuno" },
          { etiqueta: "29", toma: 116, tipo: "postprandial" },
          { etiqueta: "30", toma: 86, tipo: "ayuno" },
          { etiqueta: "30", toma: 123, tipo: "postprandial" },
        ],
      },
      "2026-05": {
        etiquetaFiltro: "Mayo - 2026",
        puntos: [
          { etiqueta: "1", toma: 85, tipo: "ayuno" },
          { etiqueta: "1", toma: 121, tipo: "postprandial" },
          { etiqueta: "2", toma: 83, tipo: "ayuno" },
          { etiqueta: "2", toma: 118, tipo: "postprandial" },
          { etiqueta: "3", toma: 87, tipo: "ayuno" },
          { etiqueta: "3", toma: 125, tipo: "postprandial" },
          { etiqueta: "4", toma: 90, tipo: "ayuno" },
          { etiqueta: "4", toma: 130, tipo: "postprandial" },
          { etiqueta: "5", toma: 88, tipo: "ayuno" },
          { etiqueta: "5", toma: 127, tipo: "postprandial" },
          { etiqueta: "6", toma: 84, tipo: "ayuno" },
          { etiqueta: "6", toma: 119, tipo: "postprandial" },
          { etiqueta: "7", toma: 85, tipo: "ayuno" },
          { etiqueta: "7", toma: 122, tipo: "postprandial" },
          { etiqueta: "8", toma: 89, tipo: "ayuno" },
          { etiqueta: "8", toma: 128, tipo: "postprandial" },
          { etiqueta: "9", toma: 91, tipo: "ayuno" },
          { etiqueta: "9", toma: 133, tipo: "postprandial" },
          { etiqueta: "10", toma: 88, tipo: "ayuno" },
          { etiqueta: "10", toma: 126, tipo: "postprandial" },
          { etiqueta: "11", toma: 84, tipo: "ayuno" },
          { etiqueta: "11", toma: 120, tipo: "postprandial" },
          { etiqueta: "12", toma: 82, tipo: "ayuno" },
          { etiqueta: "12", toma: 117, tipo: "postprandial" },
          { etiqueta: "13", toma: 86, tipo: "ayuno" },
          { etiqueta: "13", toma: 123, tipo: "postprandial" },
          { etiqueta: "14", toma: 90, tipo: "ayuno" },
          { etiqueta: "14", toma: 131, tipo: "postprandial" },
          { etiqueta: "15", toma: 92, tipo: "ayuno" },
          { etiqueta: "15", toma: 136, tipo: "postprandial" },
          { etiqueta: "16", toma: 89, tipo: "ayuno" },
          { etiqueta: "16", toma: 129, tipo: "postprandial" },
          { etiqueta: "17", toma: 85, tipo: "ayuno" },
          { etiqueta: "17", toma: 121, tipo: "postprandial" },
          { etiqueta: "18", toma: 83, tipo: "ayuno" },
          { etiqueta: "18", toma: 118, tipo: "postprandial" },
          { etiqueta: "19", toma: 87, tipo: "ayuno" },
          { etiqueta: "19", toma: 124, tipo: "postprandial" },
          { etiqueta: "20", toma: 91, tipo: "ayuno" },
          { etiqueta: "20", toma: 132, tipo: "postprandial" },
          { etiqueta: "21", toma: 93, tipo: "ayuno" },
          { etiqueta: "21", toma: 137, tipo: "postprandial" },
          { etiqueta: "22", toma: 89, tipo: "ayuno" },
          { etiqueta: "22", toma: 128, tipo: "postprandial" },
          { etiqueta: "23", toma: 86, tipo: "ayuno" },
          { etiqueta: "23", toma: 122, tipo: "postprandial" },
          { etiqueta: "24", toma: 84, tipo: "ayuno" },
          { etiqueta: "24", toma: 119, tipo: "postprandial" },
          { etiqueta: "25", toma: 88, tipo: "ayuno" },
          { etiqueta: "25", toma: 126, tipo: "postprandial" },
          { etiqueta: "26", toma: 90, tipo: "ayuno" },
          { etiqueta: "26", toma: 131, tipo: "postprandial" },
          { etiqueta: "27", toma: 87, tipo: "ayuno" },
          { etiqueta: "27", toma: 125, tipo: "postprandial" },
          { etiqueta: "28", toma: 85, tipo: "ayuno" },
          { etiqueta: "28", toma: 121, tipo: "postprandial" },
          { etiqueta: "29", toma: 83, tipo: "ayuno" },
          { etiqueta: "29", toma: 117, tipo: "postprandial" },
          { etiqueta: "30", toma: 86, tipo: "ayuno" },
          { etiqueta: "30", toma: 123, tipo: "postprandial" },
          { etiqueta: "31", toma: 90, tipo: "ayuno" },
          { etiqueta: "31", toma: 130, tipo: "postprandial" },
        ],
      },
    },
  },

  ano: {
    metadatos: {
      unidad: "mg/dL",
      resolucion: "mes",
      periodo: "ano",
    },
    filtros: [
      { value: "2024", label: "2024" },
      { value: "2025", label: "2025" },
      { value: "2026", label: "2026" },
    ],
    seleccionActual: "2026",
    seriesPorFiltro: {
      "2024": {
        etiquetaFiltro: "2024",
        puntos: [
          { etiqueta: "ene", toma: 89, tipo: "ayuno" },
          { etiqueta: "ene", toma: 126, tipo: "postprandial" },
          { etiqueta: "feb", toma: 87, tipo: "ayuno" },
          { etiqueta: "feb", toma: 123, tipo: "postprandial" },
          { etiqueta: "mar", toma: 90, tipo: "ayuno" },
          { etiqueta: "mar", toma: 129, tipo: "postprandial" },
          { etiqueta: "abr", toma: 88, tipo: "ayuno" },
          { etiqueta: "abr", toma: 124, tipo: "postprandial" },
          { etiqueta: "may", toma: 86, tipo: "ayuno" },
          { etiqueta: "may", toma: 121, tipo: "postprandial" },
          { etiqueta: "jun", toma: 85, tipo: "ayuno" },
          { etiqueta: "jun", toma: 119, tipo: "postprandial" },
          { etiqueta: "jul", toma: 87, tipo: "ayuno" },
          { etiqueta: "jul", toma: 122, tipo: "postprandial" },
          { etiqueta: "ago", toma: 88, tipo: "ayuno" },
          { etiqueta: "ago", toma: 125, tipo: "postprandial" },
          { etiqueta: "sep", toma: 90, tipo: "ayuno" },
          { etiqueta: "sep", toma: 128, tipo: "postprandial" },
          { etiqueta: "oct", toma: 91, tipo: "ayuno" },
          { etiqueta: "oct", toma: 131, tipo: "postprandial" },
          { etiqueta: "nov", toma: 89, tipo: "ayuno" },
          { etiqueta: "nov", toma: 127, tipo: "postprandial" },
          { etiqueta: "dic", toma: 88, tipo: "ayuno" },
          { etiqueta: "dic", toma: 124, tipo: "postprandial" },
        ],
      },
      "2025": {
        etiquetaFiltro: "2025",
        puntos: [
          { etiqueta: "ene", toma: 88, tipo: "ayuno" },
          { etiqueta: "ene", toma: 124, tipo: "postprandial" },
          { etiqueta: "feb", toma: 86, tipo: "ayuno" },
          { etiqueta: "feb", toma: 120, tipo: "postprandial" },
          { etiqueta: "mar", toma: 89, tipo: "ayuno" },
          { etiqueta: "mar", toma: 127, tipo: "postprandial" },
          { etiqueta: "abr", toma: 87, tipo: "ayuno" },
          { etiqueta: "abr", toma: 123, tipo: "postprandial" },
          { etiqueta: "may", toma: 85, tipo: "ayuno" },
          { etiqueta: "may", toma: 119, tipo: "postprandial" },
          { etiqueta: "jun", toma: 84, tipo: "ayuno" },
          { etiqueta: "jun", toma: 117, tipo: "postprandial" },
          { etiqueta: "jul", toma: 86, tipo: "ayuno" },
          { etiqueta: "jul", toma: 121, tipo: "postprandial" },
          { etiqueta: "ago", toma: 87, tipo: "ayuno" },
          { etiqueta: "ago", toma: 124, tipo: "postprandial" },
          { etiqueta: "sep", toma: 89, tipo: "ayuno" },
          { etiqueta: "sep", toma: 128, tipo: "postprandial" },
          { etiqueta: "oct", toma: 90, tipo: "ayuno" },
          { etiqueta: "oct", toma: 130, tipo: "postprandial" },
          { etiqueta: "nov", toma: 88, tipo: "ayuno" },
          { etiqueta: "nov", toma: 126, tipo: "postprandial" },
          { etiqueta: "dic", toma: 87, tipo: "ayuno" },
          { etiqueta: "dic", toma: 122, tipo: "postprandial" },
        ],
      },
      "2026": {
        etiquetaFiltro: "2026",
        puntos: [
          { etiqueta: "ene", toma: 86, tipo: "ayuno" },
          { etiqueta: "ene", toma: 121, tipo: "postprandial" },
          { etiqueta: "feb", toma: 84, tipo: "ayuno" },
          { etiqueta: "feb", toma: 118, tipo: "postprandial" },
          { etiqueta: "mar", toma: 88, tipo: "ayuno" },
          { etiqueta: "mar", toma: 126, tipo: "postprandial" },
          { etiqueta: "abr", toma: 87, tipo: "ayuno" },
          { etiqueta: "abr", toma: 124, tipo: "postprandial" },
          { etiqueta: "may", toma: 85, tipo: "ayuno" },
          { etiqueta: "may", toma: 122, tipo: "postprandial" },
          { etiqueta: "jun", toma: 83, tipo: "ayuno" },
          { etiqueta: "jun", toma: 117, tipo: "postprandial" },
          { etiqueta: "jul", toma: 84, tipo: "ayuno" },
          { etiqueta: "jul", toma: 119, tipo: "postprandial" },
          { etiqueta: "ago", toma: 86, tipo: "ayuno" },
          { etiqueta: "ago", toma: 123, tipo: "postprandial" },
          { etiqueta: "sep", toma: 88, tipo: "ayuno" },
          { etiqueta: "sep", toma: 127, tipo: "postprandial" },
          { etiqueta: "oct", toma: 89, tipo: "ayuno" },
          { etiqueta: "oct", toma: 129, tipo: "postprandial" },
          { etiqueta: "nov", toma: 87, tipo: "ayuno" },
          { etiqueta: "nov", toma: 125, tipo: "postprandial" },
          { etiqueta: "dic", toma: 86, tipo: "ayuno" },
          { etiqueta: "dic", toma: 122, tipo: "postprandial" },
        ],
      },
    },
  },
};

export const DataGlucosaDiariaContrato = {
  metadatos: {
    unidad: "mg/dL",
    resolucion: "hora",
    periodo: "dia",
  },
  filtros: [{ value: "2026-05-06", label: "06 May 2026" }],
  seleccionActual: "2026-05-06",
  medicionesPorFiltro: {
    "2026-05-06": {
      etiquetaFiltro: "06 May 2026",
      puntos: [
        {
          id: "glu-1",
          fechaHoraISO: "2026-05-06T10:00:00",
          hora: 10,
          toma: 60,
          horaLabel: "10:00 am",
          tipo: "ayuno",
          contexto: "reposo",
          metodo: "capilar",
        },
        {
          id: "glu-2",
          fechaHoraISO: "2026-05-06T14:00:00",
          hora: 14,
          toma: 65,
          horaLabel: "02:00 pm",
          tipo: "postprandial",
          contexto: "actividad",
          metodo: "capilar",
        },
        {
          id: "glu-3",
          fechaHoraISO: "2026-05-06T18:04:00",
          hora: 18.07,
          toma: 79,
          horaLabel: "06:04 pm",
          tipo: "postprandial",
          contexto: "reposo",
          metodo: "cgm",
        },
      ],
    },
  },
};
